version: '2'

services:
  app:
   image: ganjoorswiftapi
   ports:
     - "7080:7080"
   links:
     - db:mysql
   depends_on:
     - db
 
  db:
   image: ganjoor/ganjoor-db
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: ganjoor